---
- name: Install required packages
  ansible.builtin.include_tasks: prepare.yml

- name: Configure pbr service settings
  ansible.builtin.include_tasks: service.yml
  when: pbr_service | length > 0

- name: Configure pbr policies
  ansible.builtin.include_tasks: policy.yml
  loop: "{{ pbr_policies | default([]) }}"

- name: Apply changes and reload pbr
  uci:
    command: commit
  notify: Reload pbr
