---
- name: Configure device section
  ansible.builtin.include_tasks: device.yml
  loop: "{{ wireless_devices | default([]) }}"

- name: Configure interface section
  ansible.builtin.include_tasks: interface.yml
  loop: "{{ wireless_interfaces | default([]) }}"

- name: Apply changes and reload wireless
  uci:
    command: commit
  notify: Reload wireless
