---
- name: Remove non-mesh wpad packages
  opkg:
    name: "{{ item }}"
    state: absent
  loop: "{{ mesh11sd_non_mesh_pkgs }}"

- name: Update opkg cache
  ansible.builtin.command:
    cmd: opkg update
  changed_when: false

- name: Install mesh packages
  opkg:
    name: "{{ item }}"
    state: present
  loop: "{{ mesh11sd_pkgs }}"
