---
- name: Configure system section
  ansible.builtin.include_tasks: system.yml
  when: system_settings | length > 0

- name: Apply changes and reload system
  block:
    - name: Commit changes
      uci:
        command: commit
      notify: Reload system

    - name: Reload system service
      ansible.builtin.meta: flush_handlers
