---
- name: Configure globals section
  ansible.builtin.include_tasks: globals.yml
  when: network_globals | length > 0

- name: Configure device section
  ansible.builtin.include_tasks: device.yml
  loop: "{{ network_devices | default([]) }}"

- name: Configure interface section
  ansible.builtin.include_tasks: interface.yml
  loop: "{{ network_interfaces | default([]) }}"

- name: Configure rule section
  ansible.builtin.include_tasks: rule.yml
  loop: "{{ network_rules | default([]) }}"

- name: Configure route section
  ansible.builtin.include_tasks: route.yml
  loop: "{{ network_routes | default([]) }}"

- name: Apply changes and reload network
  uci:
    command: commit
  notify: Reload network
