---
- name: Configure defaults section
  ansible.builtin.include_tasks: defaults.yml
  when: firewall_defaults | length > 0

- name: Configure zone section
  ansible.builtin.include_tasks: zone.yml
  loop: "{{ firewall_zones | default([]) }}"

- name: Configure forwarding section
  ansible.builtin.include_tasks: forwarding.yml
  loop: "{{ firewall_forwardings | default([]) }}"

- name: Configure rule section
  ansible.builtin.include_tasks: rule.yml
  loop: "{{ firewall_rules | default([]) }}"

- name: Configure redirect section
  ansible.builtin.include_tasks: redirect.yml
  loop: "{{ firewall_redirects | default([]) }}"

- name: Configure ipset section
  ansible.builtin.include_tasks: ipset.yml
  loop: "{{ firewall_ipsets | default([]) }}"

- name: Configure nat section
  ansible.builtin.include_tasks: nat.yml
  loop: "{{ firewall_nats | default([]) }}"

- name: Apply changes and reload firewall
  uci:
    command: commit
  notify: Reload firewall
