---
# Configure common options
- name: Configure common options
  uci:
    command: "set"
    config: "dhcp"
    section: "@dnsmasq[0]"
    type: "dnsmasq"
    value:
      authoritative: "{{ dhcp_common.authoritative | default(omit) }}"
      boguspriv: "{{ dhcp_common.boguspriv | default(omit) }}"
      cachesize: "{{ dhcp_common.cachesize | default(omit) }}"
      domain: "{{ dhcp_common.domain | default(omit) }}"
      domainneeded: "{{ dhcp_common.domainneeded | default(omit) }}"
      dnssec: "{{ dhcp_common.dnssec | default(omit) }}"
      dnsseccheckunsigned: "{{ dhcp_common.dnsseccheckunsigned | default(omit) }}"
      expandhosts: "{{ dhcp_common.expandhosts | default(omit) }}"
      filterwin2k: "{{ dhcp_common.filterwin2k | default(omit) }}"
      fqdn: "{{ dhcp_common.fqdn | default(omit) }}"
      leasefile: "{{ dhcp_common.leasefile | default(omit) }}"
      local: "{{ dhcp_common.local | default(omit) }}"
      localise_queries: "{{ dhcp_common.localise_queries | default(omit) }}"
      localservice: "{{ dhcp_common.localservice | default(omit) }}"
      nonegcache: "{{ dhcp_common.nonegcache | default(omit) }}"
      nonwildcard: "{{ dhcp_common.nonwildcard | default(omit) }}"
      readethers: "{{ dhcp_common.readethers | default(omit) }}"
      rebind_protection: "{{ dhcp_common.rebind_protection | default(omit) }}"
      rebind_localhost: "{{ dhcp_common.rebind_localhost | default(omit) }}"
      rebind_domain: "{{ dhcp_common.rebind_domain | default([]) | join(' ') }}"
      resolvfile: "{{ dhcp_common.resolvfile | default([]) | join(' ') }}"
      server: "{{ dhcp_common.server | default([]) | join(' ') }}"
      serverlist: "{{ dhcp_common.serverlist | default(omit) }}"
      address: "{{ dhcp_common.address | default([]) | join(' ') }}"
      allservers: "{{ dhcp_common.allservers | default(omit) }}"
