---
- name: Configure dnsmasq section
  ansible.builtin.include_tasks: dnsmasq.yml
  when: dhcp_common | length > 0

- name: Configure dhcp section
  ansible.builtin.include_tasks: dhcp.yml
  loop: "{{ dhcp_pools | default([]) }}"

- name: Configure host section
  ansible.builtin.include_tasks: host.yml
  loop: "{{ dhcp_leases | default([]) }}"

- name: Apply changes and reload dhcp
  uci:
    command: commit
  notify: Reload dhcp
