---
- name: Install required packages
  ansible.builtin.include_tasks: prepare.yml

- name: Configure node_exporter service
  ansible.builtin.include_tasks: configure.yml
  when: node_exporter_settings | length > 0

- name: Apply changes and reload node_exporter service
  uci:
    command: commit
  notify: Reload node_exporter
