---
- name: Update opkg cache
  ansible.builtin.command:
    cmd: opkg update
  changed_when: false

- name: Install node_exporter packages
  opkg:
    name: "{{ item }}"
    state: present
  loop: "{{ node_exporter_pkgs }}"
