---
# Reboot device
- name: Reboot device
  ansible.builtin.command:
    cmd: "reboot"
  register: reboot_device_status
  changed_when: reboot_device_status != 0

# Wait for device to boot up
- name: Wait for device to boot up
  ansible.builtin.wait_for_connection:
    delay: 30
    timeout: 300
