---
# Fix ath10k drivers
# https://openwrt.org/docs/guide-user/network/wifi/mesh/80211s#wireless_hardware_support
- name: Fix ath10k drivers
  ansible.builtin.include_tasks: ath10k.yml
  when: batman_enabled and ath10k_ct_fix

# Install required packages
- name: Install required packages
  ansible.builtin.include_tasks: prepare.yml
  when: batman_enabled

# Create B.A.T.M.A.N. wireless interfaces
- name: Create batman wireless interfaces
  ansible.builtin.include_role:
    name: "wireless"
  vars:
    wireless_interfaces: "{{ batman_wireless_interfaces | default([]) }}"
  when: batman_enabled

# Configure B.A.T.M.A.N. network interfaces
- name: Configure batman network interfaces
  ansible.builtin.include_tasks: interface.yml
  loop: "{{ batman_network_interfaces | default([]) }}"
  when: batman_enabled

# Apply changes and reload wireless service
- name: Apply changes and reload wireless
  when: batman_enabled
  uci:
    command: commit
  notify: Reload wireless
