---
- name: Get rootfs block device name  # noqa: command-instead-of-module
  ansible.builtin.command:
    cmd: 'sed -n -e "/\s\/overlay\s.*$/s///p" /etc/mtab'  # yamllint disable-line rule:quoted-strings
  register: extroot_rootfs_block_device_name
  changed_when: false

- name: Set rootfs block device name fact
  ansible.builtin.set_fact:
    extroot_block_device_name: "{{ extroot_rootfs_block_device_name.stdout }}"

- name: Mount rootfs data to another directory
  block:
    - name: Add new mount point for root
      uci:
        command: add
        config: fstab
        section: rwm
        type: mount

    - name: Configure new mount point for root
      uci:
        command: set
        config: fstab
        section: rwm
        type: mount
        value:
          device: "{{ extroot_block_device_name }}"
          target: /rwm

- name: Get external usb device uuid
  ansible.builtin.command:
    cmd: 'block info /dev/{{ extroot_device }}1 | grep -o -e "UUID=\S*"'  # yamllint disable-line rule:quoted-strings
  register: extroot_external_usb_device_uuid
  changed_when: false

- name: Set external usb device uuid fact
  ansible.builtin.set_fact:
    extroot_usb_device_uuid: '{{ extroot_external_usb_device_uuid.stdout | regex_search(''(?<=")(.*?)(?=")'') }}'

- name: Mount external usb as overlayfs
  block:
    - name: Add overlay mount point
      uci:
        command: add
        config: fstab
        section: overlay
        type: mount

    - name: Configure overlay mount point
      uci:
        command: set
        config: fstab
        section: overlay
        type: mount
        value:
          uuid: "{{ extroot_usb_device_uuid }}"
          target: /overlay
