---
- name: Check extroot status
  ansible.builtin.include_tasks: check.yml
  when: extroot_enabled

- name: Install required packages
  ansible.builtin.include_tasks: prepare.yml
  when: extroot_configure

- name: Configure external usb
  ansible.builtin.include_tasks: usb.yml
  when: extroot_configure

- name: Configure fstab
  ansible.builtin.include_tasks: fstab.yml
  when: extroot_configure

- name: Configure system
  ansible.builtin.include_tasks: system.yml
  when: extroot_configure

- name: Apply changes and reboot device
  when: extroot_configure
  block:
    - name: Commit changes
      uci:
        command: commit
      notify: [Reboot device, Wait for device to boot up]

    - name: Reboot device
      ansible.builtin.meta: flush_handlers
