---
- name: Install required packages
  ansible.builtin.include_tasks: prepare.yml

- name: Configure wireguard interfaces
  ansible.builtin.include_tasks: server.yml
  loop: "{{ wireguard_interfaces | default([]) }}"

- name: Configure wireguard peers
  ansible.builtin.include_tasks: peer.yml
  loop: "{{ wireguard_peers | default([]) }}"
  loop_control:
    loop_var: wgpeer
    label: "{{ wgpeer }}"

- name: Apply changes and reload network
  uci:
    command: commit
  notify: Reload network
