---
# system section
dropbear:
  enable: ""
  verbose: ""
  BannerFile: ""
  PasswordAuth: ""
  Port: ""
  RootPasswordAuth: ""
  RootLogin: ""
  GatewayPorts: ""
  Interface: ""
  keyfile: ""
  SSHKeepAlive: ""
  IdleTimeout: ""
  mdns: ""
  MaxAuthTries: ""
  RecvWindowSize: ""
